### ISSUE TITLE
Navbar's movement could be smoother.

### ISSUE THREAD

**Issue by rymatech** [fac-17/ABCD-week1#45]
Try adding the below code to your css, to make the navbar smoother. 

```
html {
  scroll-behavior: smooth;
}
```

**Comment by rymatech** [comment]
The above code will create this affect https://www.w3schools.com/cssref/tryit.asp?filename=trycss_scroll_behavior

**Comment by frannyfra** [comment]
It worked !!! Thanks :smile:
