### ISSUE TITLE
Great choice of fonts but text in input boxes needs adjusting. 

### ISSUE THREAD

**Issue by rymatech** [fac-17/ABCD-week1#48]
Font size in form is very small perhaps consider increasing. 

With inputs boxes I always like to disable the built-in highlighting although this is personal preference. 

```
input:focus {
    outline: none;
}
```

https://stackoverflow.com/questions/1457849/how-to-remove-the-border-highlight-on-an-input-text-element

**Comment by sarahyjja** [comment]
cool!
